# Generated by Django 3.2.2 on 2021-05-26 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('M', 'manager'), ('H', 'head'), ('C', 'customer')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('meal', models.CharField(choices=[('조식', '조식'), ('중식', '중식'), ('석식', '석식')], max_length=2)),
                ('sale_start_time', models.TimeField()),
                ('sale_end_time', models.TimeField()),
                ('sale_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('foods', models.TextField()),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.cafeteria')),
            ],
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.profile'),
        ),
    ]
