# Generated by Django 3.2.2 on 2021-05-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteria',
            name='manager',
        ),
        migrations.AddField(
            model_name='profile',
            name='Cafeteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.cafeteria'),
        ),
    ]
