# Generated by Django 3.2.2 on 2021-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210529_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('판매 가능', '판매 가능'), ('판매 중지', '판매 중지')], max_length=20, null=True),
        ),
    ]
